### ISSUE TITLE
Non-Code Todo Checklist

### ISSUE THREAD

**Issue by ehlewis** [ehlewis/knotter#7]
- [x] Meet for layout and goals
- [x] Sign equity document
- [x] Create social media accounts
- [x] Choose a domain name
- [ ] Determine which features will be in link+
- [x] How to generate revenue
- [x] Figure out best method for mobile app
- [x] Draw out flow of web app
- [x] Get SSL Cert with certbot
- [x] Get in kahoots with Plaid
- [ ] Blog-ish style thingy for upcoming features in progress
- [ ] Create terms of service
- [x] Create short term outlook timeline
- [x] Create webpage design drawup
- [x] Comment code so other people can read it
- [ ] Create API .md so all available functions are easily viewed
- [x] Make a PWA
- [ ] Set up email for knotter.co domain
- [ ] Get knotter.com domain
- [ ] Find an ad engine api
